name: K8s Demo Workflow

on: 
  push:
    branches:
      - main

jobs:
  deploy-code:
    runs-on: ubuntu-latest
    steps:
      # Places the repository in the runner (GitHub temporary VM)
      - name: Checkout repo
        uses: actions/checkout@v5

      # optional step: build and push docker image

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v5.1.0
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: $${{ secrets.AWS_REGION }}

      - name: Configure kubeconfig (for EKS)
        run: aws eks update-kubeconfig --name ${{ secrets.AWS_CLUSTER_NAME }} --region ${{ secrets.AWS_REGION }}

      - name: Deploy our manifest files
        run:
          kubectl apply -f .

